routes/web.php
<?php

use Carbon\Carbon;
use App\Models\User;
use Inertia\Inertia;
use App\Models\Grade;
use App\Models\TempClass;
use App\Models\TempStudent;
use App\Models\MunaqosahTahfidz;
use Illuminate\Support\Facades\DB;
use App\Http\Livewire\JournalIndex;
use App\Models\ExtracurricularData;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redis;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\CobaController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\SiswaController;
use Psy\CodeCleaner\ValidConstructorPass;
use PHPUnit\Framework\Constraint\Operator;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\OperatorController;
use App\Http\Controllers\PresenceController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\AcaraController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\MunaqosahTahfidzController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\ExtracurricularDataController;

// developer mode only
// comment if production starting
// =====================================
// function __construct()
// {
//     Artisan::call('config:clear');
//     Artisan::call('cache:clear');
//     Artisan::call('config:cache');
//     Artisan::call('view:clear');
//     Artisan::call('route:cache');
// }
// =====================================

Route::get(
    'rj',
    function () {
        Artisan::call('queue:work');
        return 'Job Berhasil di hapus';
    }
);

Route::get(
    'cj',
    function () {
        Artisan::call('queue:clear');
    }
);

Route::get('cekImagick', function () {

    if (!extension_loaded('imagick')) {
        echo 'imagick not installed';
    }
    // phpinfo();
});

Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/', [HomeController::class, 'index']);
// Route::get('/login_siswa',function (){
//     return view('auth.login_siswa');
// })->name('login.siswa');
Route::get('/login_siswa', [LoginController::class, 'siswaLogin'])->name('login.siswa');

// ROUTE::ADMIN
Route::middleware('role:admin')->group(function () {
    Route::resource('user', UserController::class);
    Route::resource('grade', GradeController::class);
    Route::prefix('/admin')->group(function () {

        Route::put('/presence/setting', [AdminController::class, 'updateSettingPresence'])->name('admin.update.setPresence');
        Route::get('/db_settings', [AdminController::class, 'dbSettings'])->name('admin.DBset');
        Route::get('/edit_set_presence/{id}', [AdminController::class, 'editPresenceSetting'])->name('admin.editSettingPresence');
        Route::get('/edit_db_set/{id}', [AdminController::class, 'editDbset'])->name('admin.editDbset');
        Route::delete('/hapus_db_set/{id}', [AdminController::class, 'hapusDbset'])->name('admin.hapusDbset');

        Route::get('/users', [UserController::class, 'index'])->name('admin.users');
        Route::get('/tambah_user', [UserController::class, 'addUser'])->name('tambah_user');
        // Route::get('/tambah_user', function () {
        //     return view('user.create');
        // })->name('tambah_user');
        Route::post('/users/import', [UserController::class, 'import'])->name('admin.import_users');

        Route::post('/students/import/tempstudent', [StudentController::class, 'importTempStudent'])->name('admin.import_temp_students');
        Route::post('/students/import', [StudentController::class, 'import'])->name('admin.import_students');
        Route::post('/teachers/import', [TeacherController::class, 'import'])->name('admin.import_teachers');
        Route::get('/students/export', [StudentController::class, 'export'])->name('admin.export_students');
        Route::get('/teachers/export', [TeacherController::class, 'export'])->name('admin.export_teachers');

        Route::post('/create_user', [AdminController::class, 'createUser'])->name('admin.create_user');
    });
});

// ROUTE::OPERATOR
Route::middleware('role:operator|admin')->group(function () {
    Route::prefix('operator')->group(function () {
        Route::get('/students', [OperatorController::class, 'getStudents'])->name('students');
        Route::get('/student/{id}', [OperatorController::class, 'getStudent'])->name('student_detail');
        Route::get('/student/edit/{id}', [OperatorController::class, 'editStudent'])->name('student_edit');
        Route::put('/student/edit/{id}', [OperatorController::class, 'updateStudent'])->name('student_update');
        Route::delete('/student/{id}', [OperatorController::class, 'destroy'])->name('student_delete');
        Route::get('/import', [OperatorController::class, 'import']);

        Route::get('/teachers', [TeacherController::class, 'index'])->name('teachers');
        Route::get('/teacher/{id}', [TeacherController::class, 'show'])->name('teacher_detail');
        Route::get('/teacher/edit/{id}', [TeacherController::class, 'edit'])->name('teacher_edit');
        Route::put('/teacher/edit/{id}', [TeacherController::class, 'update'])->name('teacher_update');
        Route::delete('/teacher/{id}', [TeacherController::class, 'destroy'])->name('teacher_delete');

        Route::get('/revisi_data', [OperatorController::class, 'revisiData'])->name('operator.revisi_data');
        Route::get('/compare_revisi/{id}', [OperatorController::class, 'compareRevisi'])->name('compare_revisi');

        Route::get('/identitas_sekolah', [OperatorController::class, 'schoolId'])->name('operator.school_id');
        Route::get('/identitas_sekolah/{id}', [OperatorController::class, 'editSchool'])->name('operator.edit_schoolid');
        Route::put('/identitas_sekolah/{id}', [OperatorController::class, 'updateSchool'])->name('operator.update_schoolid');

        Route::get('/siswa_kelas/{id}', [OperatorController::class, 'siswaKelas'])->name('operator.siswa_kelas');
    });
});


// ROUTE::GURU
Route::get('/guru/input', [TeacherController::class, 'input'])->name('teachers_page.input');
Route::middleware('role:guru|karyawan}')->group(function () {
    Route::prefix('guru')->group(function () {
        route::post('input', [TeacherController::class, 'inputData'])->name('teachers.input_data');
        route::get('/biodata', [TeacherController::class, 'biodata'])->name('teachers.biodata');
        Route::get('/edit', [TeacherController::class, 'editTeacher'])->name('teachers.edit');
        Route::put('/edit', [TeacherController::class, 'updateTeacher'])->name('teachers.update');

        Route::get('/upload_dokumen', [TeacherController::class, 'uploadDokumen'])->name('teachers.upload_dokumen');

        route::get('/tambah_pendidikan', function () {
            return view('teachers_page.tambah_pendidikan');
        })->name('teachers.tambah_pendidikan');
        route::post('/tambah_pendidikan', [TeacherController::class, 'inputPendidikan'])->name('teachers.input_pendidikan');

        route::get('/tambah_anak', function () {
            return view('teachers_page.tambah_anak');
        })->name('teachers.tambah_anak');
        route::post('/tambah_anak', [TeacherController::class, 'inputAnak'])->name('teachers.input_anak');

        route::get('/tambah_diklat', function () {
            return view('teachers_page.tambah_diklat');
        })->name('teachers.tambah_diklat');
        route::post('/tambah_diklat', [TeacherController::class, 'inputDiklat'])->name('teachers.input_diklat');

        route::delete('/hapus_pendidikan/{id}', [TeacherController::class, 'hapusPendidikan'])->name('teachers.hapus_pendidikan');
        route::delete('/hapus_diklat/{id}', [TeacherController::class, 'hapusDiklat'])->name('teachers.hapus_diklat');
        route::delete('/hapus_anak/{id}', [TeacherController::class, 'hapusAnak'])->name('teachers.hapus_anak');

        route::get('/journal', function () {
            return view('teachers_page.jurnal');
        });
        route::get('/journal_export', [JournalIndex::class, 'exportExcel'])->name('journal_export');
    });
});


// ROUTE::SISWA
Route::middleware('role:siswa')->group(function () {
    Route::prefix('siswa')->group(function () {
        Route::get('/data', [SiswaController::class, 'data'])->name('siswa.data');
        Route::get('/student/edit', [SiswaController::class, 'editStudent'])->name('siswa_edit');
        Route::put('/student/edit', [SiswaController::class, 'ajukanUpdate'])->name('siswa_update');
        Route::get('/prestasi', [SiswaController::class, 'achievement'])->name('siswa_prestasi');
        Route::post('/input_prestasi', [SiswaController::class, 'inputAchievement'])->name('siswa.input_prestasi');
        Route::delete('/hapus_prestasi/{id}', [SiswaController::class, 'deleteAchievement'])->name('siswa.hapus_prestasi');
        Route::get('/pengajuan_revisi', [SiswaController::class, 'pengajuanRevisi'])->name('siswa.pengajuan_revisi');
        Route::get('/upload_dokumen', [SiswaController::class, 'uploadDokumen'])->name('siswa.upload_dokumen');
    });
});

Route::post('/upload', [DocumentController::class, 'store'])->name('document.store');

route::get('keluar', [LoginController::class, 'keluar'])->name('keluar');
route::get('klaim_nis', function () {
    return view('auth.cek_nis');
})->name('klaim_nis');
route::post('input_klaim_nis', [SocialiteController::class, 'inputKlaimNis'])->name('input_klaim_nis');

route::get('sebagai', function () {
    return view('auth.sebagai');
})->name('tentukan_role');

route::get('cek_nis', [LoginController::class, 'cekNis'])->name('cek_nis');

//Login Google

resources/views/admin/db_settings.blade.php
    @extends('layout.master')
    @section('page_judul', 'Database Setting')
    @section('content')
        <div class="card rounded p-3">
            @if ($collection->count() == 0)
                <div class="card text-center p-4">
                    <h1 class="display-6">
                        Maaf belum ada data yang tersimpan ...
                    </h1>
                </div>
            @else
                <p class="fs-4">Apps Setting</p>
                <div class="table-responsive">
                    <table id="data" class="table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Value</th>
                                <th>Info</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($collection as $item)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ $item->value }}</td>
                                    <td>{{ $item->info }}</td>
                                    <td>
                                        <form action="{{ route('admin.hapusDbset', $item->id) }}" method="POST">
                                            </a>
                                            <a href="{{ route('admin.editDbset', $item->id) }}" class="btn btn-primary">
                                                <span><i class="las la-edit"></i></span>
                                            </a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-primary"
                                                onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">
                                                <span><i class="las la-trash"></i></span></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @endif
        </div>
        <div class="card rounded p-3 mt-3">
            <p class="fs-4">Time Setting</p>
            <table id="data" class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Value</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($presence as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->value }}</td>
                            <td>
                                <a href="{{ route('admin.editSettingPresence', $item->id) }}" class="btn btn-primary">
                                    <span><i class="las la-edit"></i></span>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <livewire:qrcode />
    @endsection

resources/views/admin/edit_db_set.blade.php
@extends('layout.master')
@section('page_judul', 'Edit Database Setting')
@section('content')
    <div id="page_info" class="card rounded p-3">
        <div class="py-2 my-2 clear-fix">
            <h3 class="float-start">Edit DB Setting (Developer Only)</h3>
        </div>
        <form action="#" method="POST">
            @csrf
            @method('PUT')
            <table class="table">
                <tbody>
                    <tr>
                        <td>Name</td>
                        <td>
                            <input class="form-control" type="text" name="name" value="{{ $item->name }}">
                        </td>
                    </tr>
                    <tr>
                        <td>Value</td>
                        <td><input class="form-control" type="text" name="value" value="{{ $item->value }}"></td>
                    </tr>
                    <tr>
                        <td>Info</td>
                        <td><input class="form-control" type="text" name="info" value="{{ $item->info }}"></td>
                    </tr>
                    <tr>
                        <td>Is active</td>
                        <td><input class="form-control" type="text" name="is_active" value="{{ $item->is_active }}"></td>
                    </tr>

                </tbody>
            </table>
            <a type="SUBMIT" class="btn btn-success"> Update </a>
        </form>
    </div>
@endsection

resources/views/admin/edit_presence_set.blade.php
@extends('layout.master')
@section('page_judul', 'Edit Database Setting')
@section('content')
    <div id="page_info" class="card rounded p-3">
        <div class="py-2 my-2 clear-fix">
            <h3 class="float-start">Edit Presence Setting (Developer Only)</h3>
        </div>
        <form action="{{ route('admin.update.setPresence') }}" method="POST">
            @csrf
            @method('PUT')
            <table class="table">
                <tbody>
                    <tr>
                        <td>Name</td>
                        <td>
                            <input type="hidden" name="id" value="{{ $item->id }}">
                            <input class="form-control" type="text" name="name" value="{{ $item->name }}" disabled>
                        </td>
                    </tr>
                    <tr>
                        <td>Value</td>
                        <td><input class="form-control" type="text" name="value" value="{{ $item->value }}"></td>
                    </tr>
                </tbody>
            </table>
            <button type="SUBMIT" class="btn btn-success"> Update </button>
        </form>
    </div>
@endsection

resources/views/admin/home.blade.php
@extends('layout.master')
@section('page_judul', 'Dashboard')
@section('content')
    {{-- @php
    $jml_siswa = DB::table('students')->count();
    $jml_guru = DB::table('teachers')->count();
    $jml_pegawai = DB::table('teachers')
    ->where('role_id', 5)
    ->count();
    @endphp --}}
    <div class="card rounded p-3">
        <p class="fs-4 text-center m-0">Selamat Datang di <br> Aplikasi Database SDIT HARAPAN UMAT JEMBER</p>
    </div>
    <div id="info" class="row gx-3">
        <div class="col-12 col-sm-6">
            <div class="mt-3 card rounded p-3 flex-row justify-content-between align-items-center">
                <div class="flex-fill">
                    <button class="float-start btn btn-success rounded">
                        <i class="las la-user-check la-lg"></i>
                    </button>
                    <span class="ms-2 fs-5"> Total Siswa </span>
                </div>
                <span class="bg-success p-1 px-2 fs-5 rounded text-white">{{ $jml_siswa }}</span>
            </div>
        </div>
        <div class="col-12 col-sm-6">
            <div class="mt-3 card rounded p-3 flex-row justify-content-between align-items-center">
                <div class="flex-fill">
                    <span class="float-start btn btn-success rounded">
                        <i class="las la-user-check la-lg"></i>
                    </span>
                    <span class="ms-2 fs-5"> Guru/Karyawan </span>
                </div>
                <span class="bg-success p-1 px-2 fs-5 rounded text-white">{{ $jml_guru }}</span>
            </div>
        </div>

    </div>
    <div class="card mt-3 rounded p-3">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Form</th>
                    <th scope="col">Keterangan</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th><button class="btn btn-success btn-sm rounded">
                            <i class="las la-school la-lg"></i>
                        </button></th>
                    <td>Sekolah</td>
                    <td> {{ $sekolah->nama_sekolah }}</td>
                </tr>
                <tr>
                    <th><button class="btn btn-success btn-sm rounded">
                            <i class="las la-code la-lg"></i>
                        </button></th>
                    <td>NPSN</td>
                    <td> {{ $sekolah->npsn }}</td>
                </tr>
                <tr>
                    <th><button class="btn btn-success btn-sm rounded">
                            <i class="las la-map-marked la-lg"></i>
                        </button></th>
                    <td>Alamat</td>
                    <td> {{ $sekolah->alamat_sekolah }}
                        <br>{{ $sekolah->kelurahan }} {{ $sekolah->kecamatan }} {{ $sekolah->kota }}
                        {{ $sekolah->provinsi }}
                    </td>
                </tr>
                <tr>
                    <th><button class="btn btn-success btn-sm rounded">
                            <i class="las la-atlas la-lg"></i>
                        </button></th>
                    <td>Website</td>
                    <td> <a href="https://{{ $sekolah->website }}">{{ $sekolah->website }}</a> </td>
                </tr>
                <tr>
                    <th><button class="btn btn-success btn-sm rounded">
                            <i class="las la-envelope-open-text la-lg"></i>
                        </button></th>
                    <td>Email</td>
                    <td> {{ $sekolah->email }}</td>
                </tr>
            </tbody>
        </table>
    </div>
@endsection
@section('js')

@stop

resources/views/admin/users.blade.php
    @extends('layout.master')
    @section('page_judul', 'Tambah Data User')
    <x-datatables />
    @section('content')
        <!-- Modal -->
        {{-- <div class="modal fade" id="tambahDataUser" tabindex="99" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Import User</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="{{ route('admin.import_users') }}" method="POST" enctype="multipart/form-data">
                            @method('post')
                            @csrf
                            <div class="mb-3">
                                <input type="file" name="file" class="form-control" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Import</button>
                        </form>
                    </div>
                </div>
            </div>
        </div> --}}

        <div id="page_info" class="card rounded p-3">
            <div class="mb-3">
                {{-- <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#tambahDataUser">
                    Import User
                </button> --}}
                <a href="{{ route('tambah_user') }}" type="button" class="btn btn-success">
                    Tambah User
                </a>
            </div>

            @if ($collection->count() == 0)
                Belum ada data
            @else
                <div class="table-responsive">
                    <table id="datatable" class="table" style="width:100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>Dibuat</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($collection as $item)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $item->name }}</td>
                                    <td>{{ $item->email }}</td>
                                    <td>{{ $item->created_at }}</td>
                                    <td>
                                        <form action="{{ route('user.destroy', $item->id) }}" method="POST">
                                            </a>
                                            <a href="{{ route('user.edit', $item->id) }}" class="btn btn-warning">
                                                <span><i class="las la-edit"></i></span>
                                            </a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger"
                                                onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">
                                                <span><i class="las la-trash"></i></span></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            @endif
        </div>
    @endsection